package com.ts.acl.dao;

import com.ts.acl.model.Basicinfo;
import com.ts.acl.model.BasicinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasicinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int countByExample(BasicinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int deleteByExample(BasicinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int deleteByPrimaryKey(String taxregcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int insert(Basicinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int insertBatch(List<Basicinfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int insertSelective(Basicinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    List<Basicinfo> selectByExample(BasicinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    Basicinfo selectByPrimaryKey(String taxregcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") Basicinfo record, @Param("example") BasicinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int updateByExample(@Param("record") Basicinfo record, @Param("example") BasicinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int updateByPrimaryKeySelective(Basicinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    int updateByPrimaryKey(Basicinfo record);
}