package com.pub.dic.model;

import com.ts.model.BaseVO;

/**
 * 处理意见字典表
 */

public class SjzlWrkDmClyj extends BaseVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZL_WRK_DM_CLYJ.CLYJDM
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    private String clyjdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZL_WRK_DM_CLYJ.CLYJMC
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    private String clyjmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZL_WRK_DM_CLYJ.YXBZ
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    private String yxbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SJZL_WRK_DM_CLYJ.BZ
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZL_WRK_DM_CLYJ.CLYJDM
     *
     * @return the value of SJZL_WRK_DM_CLYJ.CLYJDM
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    public String getClyjdm() {
        return clyjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZL_WRK_DM_CLYJ.CLYJDM
     *
     * @param clyjdm the value for SJZL_WRK_DM_CLYJ.CLYJDM
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    public void setClyjdm(String clyjdm) {
        this.clyjdm = clyjdm == null ? null : clyjdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZL_WRK_DM_CLYJ.CLYJMC
     *
     * @return the value of SJZL_WRK_DM_CLYJ.CLYJMC
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    public String getClyjmc() {
        return clyjmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZL_WRK_DM_CLYJ.CLYJMC
     *
     * @param clyjmc the value for SJZL_WRK_DM_CLYJ.CLYJMC
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    public void setClyjmc(String clyjmc) {
        this.clyjmc = clyjmc == null ? null : clyjmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZL_WRK_DM_CLYJ.YXBZ
     *
     * @return the value of SJZL_WRK_DM_CLYJ.YXBZ
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    public String getYxbz() {
        return yxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZL_WRK_DM_CLYJ.YXBZ
     *
     * @param yxbz the value for SJZL_WRK_DM_CLYJ.YXBZ
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    public void setYxbz(String yxbz) {
        this.yxbz = yxbz == null ? null : yxbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SJZL_WRK_DM_CLYJ.BZ
     *
     * @return the value of SJZL_WRK_DM_CLYJ.BZ
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SJZL_WRK_DM_CLYJ.BZ
     *
     * @param bz the value for SJZL_WRK_DM_CLYJ.BZ
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZL_WRK_DM_CLYJ
     *
     * @mbggenerated Wed Jan 11 10:30:31 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clyjdm=").append(clyjdm);
        sb.append(", clyjmc=").append(clyjmc);
        sb.append(", yxbz=").append(yxbz);
        sb.append(", bz=").append(bz);
        sb.append("]");
        return sb.toString();
    }
}