package com.ts.acl.model;

import com.ts.model.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class Basicinfo extends BaseVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.TAXREGCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String taxregcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERVER
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Short taxpayerver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERNAME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String taxpayername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.SHORTNAME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERORGID
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String taxpayerorgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERID
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String taxpayerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.JURPNAME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String jurpname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.IDTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String idtypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.JURPID
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String jurpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.REGTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String regtypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.SUBJECTRELATIONCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String subjectrelationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.DEPRECIATIONCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String depreciationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.GBTRADECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String gbtradecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.MANAGECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String managecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.MANAGEDOUBULECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String managedoubulecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.BUDGETLEVELCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String budgetlevelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.ACCOUNTINGMODECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String accountingmodecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.ISSINGLETAX
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Short issingletax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.ENTERPRISESORTCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String enterprisesortcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.TOWNSFLAG
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Short townsflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.PRACTICEDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Date practicedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.EADATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Date eadate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String taxpayertypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.HOLDTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String holdtypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERSTATUSCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String taxpayerstatuscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.MAINBUSIDESC
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String mainbusidesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.SIDEBUSIDESC
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String sidebusidesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.EMPLOYEEQTY
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Integer employeeqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.INCOMERESIDECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String incomeresidecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.LEVYCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String levycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.CHECKATTRIBUTE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String checkattribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.TAXOFFICIALCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String taxofficialcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERFLAG
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Short soctaxpayerflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.SUBSTITUTEORG
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String substituteorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.INSERTDEPTCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String insertdeptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.INSERTSTAFFCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String insertstaffcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.ACCEPTDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Date acceptdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERSTATUS
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String soctaxpayerstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERAPPDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Date soctaxpayerappdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.ISFREIGHTDOFOR
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Short isfreightdofor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.FREIGHTINCOME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private BigDecimal freightincome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.PERSONALFEETYPE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Short personalfeetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.CANTONCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String cantoncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.PROVINBRANCHTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private String provinbranchtypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REG_TAXPAYERBASICINFO.FIRSTACCEPTDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    private Date firstacceptdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.TAXREGCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.TAXREGCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getTaxregcode() {
        return taxregcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.TAXREGCODE
     *
     * @param taxregcode the value for TB_REG_TAXPAYERBASICINFO.TAXREGCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setTaxregcode(String taxregcode) {
        this.taxregcode = taxregcode == null ? null : taxregcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERVER
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.TAXPAYERVER
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Short getTaxpayerver() {
        return taxpayerver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERVER
     *
     * @param taxpayerver the value for TB_REG_TAXPAYERBASICINFO.TAXPAYERVER
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setTaxpayerver(Short taxpayerver) {
        this.taxpayerver = taxpayerver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERNAME
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.TAXPAYERNAME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getTaxpayername() {
        return taxpayername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERNAME
     *
     * @param taxpayername the value for TB_REG_TAXPAYERBASICINFO.TAXPAYERNAME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setTaxpayername(String taxpayername) {
        this.taxpayername = taxpayername == null ? null : taxpayername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.SHORTNAME
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.SHORTNAME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.SHORTNAME
     *
     * @param shortname the value for TB_REG_TAXPAYERBASICINFO.SHORTNAME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERORGID
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.TAXPAYERORGID
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getTaxpayerorgid() {
        return taxpayerorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERORGID
     *
     * @param taxpayerorgid the value for TB_REG_TAXPAYERBASICINFO.TAXPAYERORGID
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setTaxpayerorgid(String taxpayerorgid) {
        this.taxpayerorgid = taxpayerorgid == null ? null : taxpayerorgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERID
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.TAXPAYERID
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getTaxpayerid() {
        return taxpayerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERID
     *
     * @param taxpayerid the value for TB_REG_TAXPAYERBASICINFO.TAXPAYERID
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setTaxpayerid(String taxpayerid) {
        this.taxpayerid = taxpayerid == null ? null : taxpayerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.JURPNAME
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.JURPNAME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getJurpname() {
        return jurpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.JURPNAME
     *
     * @param jurpname the value for TB_REG_TAXPAYERBASICINFO.JURPNAME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setJurpname(String jurpname) {
        this.jurpname = jurpname == null ? null : jurpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.IDTYPECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.IDTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getIdtypecode() {
        return idtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.IDTYPECODE
     *
     * @param idtypecode the value for TB_REG_TAXPAYERBASICINFO.IDTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setIdtypecode(String idtypecode) {
        this.idtypecode = idtypecode == null ? null : idtypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.JURPID
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.JURPID
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getJurpid() {
        return jurpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.JURPID
     *
     * @param jurpid the value for TB_REG_TAXPAYERBASICINFO.JURPID
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setJurpid(String jurpid) {
        this.jurpid = jurpid == null ? null : jurpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.REGTYPECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.REGTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getRegtypecode() {
        return regtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.REGTYPECODE
     *
     * @param regtypecode the value for TB_REG_TAXPAYERBASICINFO.REGTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setRegtypecode(String regtypecode) {
        this.regtypecode = regtypecode == null ? null : regtypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.SUBJECTRELATIONCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.SUBJECTRELATIONCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getSubjectrelationcode() {
        return subjectrelationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.SUBJECTRELATIONCODE
     *
     * @param subjectrelationcode the value for TB_REG_TAXPAYERBASICINFO.SUBJECTRELATIONCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setSubjectrelationcode(String subjectrelationcode) {
        this.subjectrelationcode = subjectrelationcode == null ? null : subjectrelationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.DEPRECIATIONCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.DEPRECIATIONCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getDepreciationcode() {
        return depreciationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.DEPRECIATIONCODE
     *
     * @param depreciationcode the value for TB_REG_TAXPAYERBASICINFO.DEPRECIATIONCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setDepreciationcode(String depreciationcode) {
        this.depreciationcode = depreciationcode == null ? null : depreciationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.GBTRADECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.GBTRADECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getGbtradecode() {
        return gbtradecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.GBTRADECODE
     *
     * @param gbtradecode the value for TB_REG_TAXPAYERBASICINFO.GBTRADECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setGbtradecode(String gbtradecode) {
        this.gbtradecode = gbtradecode == null ? null : gbtradecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.MANAGECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.MANAGECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getManagecode() {
        return managecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.MANAGECODE
     *
     * @param managecode the value for TB_REG_TAXPAYERBASICINFO.MANAGECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setManagecode(String managecode) {
        this.managecode = managecode == null ? null : managecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.MANAGEDOUBULECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.MANAGEDOUBULECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getManagedoubulecode() {
        return managedoubulecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.MANAGEDOUBULECODE
     *
     * @param managedoubulecode the value for TB_REG_TAXPAYERBASICINFO.MANAGEDOUBULECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setManagedoubulecode(String managedoubulecode) {
        this.managedoubulecode = managedoubulecode == null ? null : managedoubulecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.BUDGETLEVELCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.BUDGETLEVELCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getBudgetlevelcode() {
        return budgetlevelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.BUDGETLEVELCODE
     *
     * @param budgetlevelcode the value for TB_REG_TAXPAYERBASICINFO.BUDGETLEVELCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setBudgetlevelcode(String budgetlevelcode) {
        this.budgetlevelcode = budgetlevelcode == null ? null : budgetlevelcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.ACCOUNTINGMODECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.ACCOUNTINGMODECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getAccountingmodecode() {
        return accountingmodecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.ACCOUNTINGMODECODE
     *
     * @param accountingmodecode the value for TB_REG_TAXPAYERBASICINFO.ACCOUNTINGMODECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setAccountingmodecode(String accountingmodecode) {
        this.accountingmodecode = accountingmodecode == null ? null : accountingmodecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.ISSINGLETAX
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.ISSINGLETAX
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Short getIssingletax() {
        return issingletax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.ISSINGLETAX
     *
     * @param issingletax the value for TB_REG_TAXPAYERBASICINFO.ISSINGLETAX
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setIssingletax(Short issingletax) {
        this.issingletax = issingletax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.ENTERPRISESORTCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.ENTERPRISESORTCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getEnterprisesortcode() {
        return enterprisesortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.ENTERPRISESORTCODE
     *
     * @param enterprisesortcode the value for TB_REG_TAXPAYERBASICINFO.ENTERPRISESORTCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setEnterprisesortcode(String enterprisesortcode) {
        this.enterprisesortcode = enterprisesortcode == null ? null : enterprisesortcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.TOWNSFLAG
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.TOWNSFLAG
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Short getTownsflag() {
        return townsflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.TOWNSFLAG
     *
     * @param townsflag the value for TB_REG_TAXPAYERBASICINFO.TOWNSFLAG
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setTownsflag(Short townsflag) {
        this.townsflag = townsflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.PRACTICEDATE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.PRACTICEDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Date getPracticedate() {
        return practicedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.PRACTICEDATE
     *
     * @param practicedate the value for TB_REG_TAXPAYERBASICINFO.PRACTICEDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setPracticedate(Date practicedate) {
        this.practicedate = practicedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.EADATE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.EADATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Date getEadate() {
        return eadate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.EADATE
     *
     * @param eadate the value for TB_REG_TAXPAYERBASICINFO.EADATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setEadate(Date eadate) {
        this.eadate = eadate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERTYPECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.TAXPAYERTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getTaxpayertypecode() {
        return taxpayertypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERTYPECODE
     *
     * @param taxpayertypecode the value for TB_REG_TAXPAYERBASICINFO.TAXPAYERTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setTaxpayertypecode(String taxpayertypecode) {
        this.taxpayertypecode = taxpayertypecode == null ? null : taxpayertypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.HOLDTYPECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.HOLDTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getHoldtypecode() {
        return holdtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.HOLDTYPECODE
     *
     * @param holdtypecode the value for TB_REG_TAXPAYERBASICINFO.HOLDTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setHoldtypecode(String holdtypecode) {
        this.holdtypecode = holdtypecode == null ? null : holdtypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERSTATUSCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.TAXPAYERSTATUSCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getTaxpayerstatuscode() {
        return taxpayerstatuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.TAXPAYERSTATUSCODE
     *
     * @param taxpayerstatuscode the value for TB_REG_TAXPAYERBASICINFO.TAXPAYERSTATUSCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setTaxpayerstatuscode(String taxpayerstatuscode) {
        this.taxpayerstatuscode = taxpayerstatuscode == null ? null : taxpayerstatuscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.MAINBUSIDESC
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.MAINBUSIDESC
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getMainbusidesc() {
        return mainbusidesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.MAINBUSIDESC
     *
     * @param mainbusidesc the value for TB_REG_TAXPAYERBASICINFO.MAINBUSIDESC
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setMainbusidesc(String mainbusidesc) {
        this.mainbusidesc = mainbusidesc == null ? null : mainbusidesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.SIDEBUSIDESC
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.SIDEBUSIDESC
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getSidebusidesc() {
        return sidebusidesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.SIDEBUSIDESC
     *
     * @param sidebusidesc the value for TB_REG_TAXPAYERBASICINFO.SIDEBUSIDESC
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setSidebusidesc(String sidebusidesc) {
        this.sidebusidesc = sidebusidesc == null ? null : sidebusidesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.EMPLOYEEQTY
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.EMPLOYEEQTY
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Integer getEmployeeqty() {
        return employeeqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.EMPLOYEEQTY
     *
     * @param employeeqty the value for TB_REG_TAXPAYERBASICINFO.EMPLOYEEQTY
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setEmployeeqty(Integer employeeqty) {
        this.employeeqty = employeeqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.INCOMERESIDECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.INCOMERESIDECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getIncomeresidecode() {
        return incomeresidecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.INCOMERESIDECODE
     *
     * @param incomeresidecode the value for TB_REG_TAXPAYERBASICINFO.INCOMERESIDECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setIncomeresidecode(String incomeresidecode) {
        this.incomeresidecode = incomeresidecode == null ? null : incomeresidecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.LEVYCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.LEVYCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getLevycode() {
        return levycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.LEVYCODE
     *
     * @param levycode the value for TB_REG_TAXPAYERBASICINFO.LEVYCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setLevycode(String levycode) {
        this.levycode = levycode == null ? null : levycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.CHECKATTRIBUTE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.CHECKATTRIBUTE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getCheckattribute() {
        return checkattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.CHECKATTRIBUTE
     *
     * @param checkattribute the value for TB_REG_TAXPAYERBASICINFO.CHECKATTRIBUTE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setCheckattribute(String checkattribute) {
        this.checkattribute = checkattribute == null ? null : checkattribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.TAXOFFICIALCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.TAXOFFICIALCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getTaxofficialcode() {
        return taxofficialcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.TAXOFFICIALCODE
     *
     * @param taxofficialcode the value for TB_REG_TAXPAYERBASICINFO.TAXOFFICIALCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setTaxofficialcode(String taxofficialcode) {
        this.taxofficialcode = taxofficialcode == null ? null : taxofficialcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERFLAG
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERFLAG
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Short getSoctaxpayerflag() {
        return soctaxpayerflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERFLAG
     *
     * @param soctaxpayerflag the value for TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERFLAG
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setSoctaxpayerflag(Short soctaxpayerflag) {
        this.soctaxpayerflag = soctaxpayerflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.SUBSTITUTEORG
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.SUBSTITUTEORG
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getSubstituteorg() {
        return substituteorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.SUBSTITUTEORG
     *
     * @param substituteorg the value for TB_REG_TAXPAYERBASICINFO.SUBSTITUTEORG
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setSubstituteorg(String substituteorg) {
        this.substituteorg = substituteorg == null ? null : substituteorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.INSERTDEPTCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.INSERTDEPTCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getInsertdeptcode() {
        return insertdeptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.INSERTDEPTCODE
     *
     * @param insertdeptcode the value for TB_REG_TAXPAYERBASICINFO.INSERTDEPTCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setInsertdeptcode(String insertdeptcode) {
        this.insertdeptcode = insertdeptcode == null ? null : insertdeptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.INSERTSTAFFCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.INSERTSTAFFCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getInsertstaffcode() {
        return insertstaffcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.INSERTSTAFFCODE
     *
     * @param insertstaffcode the value for TB_REG_TAXPAYERBASICINFO.INSERTSTAFFCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setInsertstaffcode(String insertstaffcode) {
        this.insertstaffcode = insertstaffcode == null ? null : insertstaffcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.ACCEPTDATE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.ACCEPTDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Date getAcceptdate() {
        return acceptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.ACCEPTDATE
     *
     * @param acceptdate the value for TB_REG_TAXPAYERBASICINFO.ACCEPTDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setAcceptdate(Date acceptdate) {
        this.acceptdate = acceptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERSTATUS
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERSTATUS
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getSoctaxpayerstatus() {
        return soctaxpayerstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERSTATUS
     *
     * @param soctaxpayerstatus the value for TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERSTATUS
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setSoctaxpayerstatus(String soctaxpayerstatus) {
        this.soctaxpayerstatus = soctaxpayerstatus == null ? null : soctaxpayerstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERAPPDATE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERAPPDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Date getSoctaxpayerappdate() {
        return soctaxpayerappdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERAPPDATE
     *
     * @param soctaxpayerappdate the value for TB_REG_TAXPAYERBASICINFO.SOCTAXPAYERAPPDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setSoctaxpayerappdate(Date soctaxpayerappdate) {
        this.soctaxpayerappdate = soctaxpayerappdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.ISFREIGHTDOFOR
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.ISFREIGHTDOFOR
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Short getIsfreightdofor() {
        return isfreightdofor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.ISFREIGHTDOFOR
     *
     * @param isfreightdofor the value for TB_REG_TAXPAYERBASICINFO.ISFREIGHTDOFOR
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setIsfreightdofor(Short isfreightdofor) {
        this.isfreightdofor = isfreightdofor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.FREIGHTINCOME
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.FREIGHTINCOME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public BigDecimal getFreightincome() {
        return freightincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.FREIGHTINCOME
     *
     * @param freightincome the value for TB_REG_TAXPAYERBASICINFO.FREIGHTINCOME
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setFreightincome(BigDecimal freightincome) {
        this.freightincome = freightincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.PERSONALFEETYPE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.PERSONALFEETYPE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Short getPersonalfeetype() {
        return personalfeetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.PERSONALFEETYPE
     *
     * @param personalfeetype the value for TB_REG_TAXPAYERBASICINFO.PERSONALFEETYPE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setPersonalfeetype(Short personalfeetype) {
        this.personalfeetype = personalfeetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.CANTONCODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.CANTONCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getCantoncode() {
        return cantoncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.CANTONCODE
     *
     * @param cantoncode the value for TB_REG_TAXPAYERBASICINFO.CANTONCODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setCantoncode(String cantoncode) {
        this.cantoncode = cantoncode == null ? null : cantoncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.PROVINBRANCHTYPECODE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.PROVINBRANCHTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public String getProvinbranchtypecode() {
        return provinbranchtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.PROVINBRANCHTYPECODE
     *
     * @param provinbranchtypecode the value for TB_REG_TAXPAYERBASICINFO.PROVINBRANCHTYPECODE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setProvinbranchtypecode(String provinbranchtypecode) {
        this.provinbranchtypecode = provinbranchtypecode == null ? null : provinbranchtypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REG_TAXPAYERBASICINFO.FIRSTACCEPTDATE
     *
     * @return the value of TB_REG_TAXPAYERBASICINFO.FIRSTACCEPTDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public Date getFirstacceptdate() {
        return firstacceptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REG_TAXPAYERBASICINFO.FIRSTACCEPTDATE
     *
     * @param firstacceptdate the value for TB_REG_TAXPAYERBASICINFO.FIRSTACCEPTDATE
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    public void setFirstacceptdate(Date firstacceptdate) {
        this.firstacceptdate = firstacceptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_REG_TAXPAYERBASICINFO
     *
     * @mbggenerated Mon Sep 05 14:20:37 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taxregcode=").append(taxregcode);
        sb.append(", taxpayerver=").append(taxpayerver);
        sb.append(", taxpayername=").append(taxpayername);
        sb.append(", shortname=").append(shortname);
        sb.append(", taxpayerorgid=").append(taxpayerorgid);
        sb.append(", taxpayerid=").append(taxpayerid);
        sb.append(", jurpname=").append(jurpname);
        sb.append(", idtypecode=").append(idtypecode);
        sb.append(", jurpid=").append(jurpid);
        sb.append(", regtypecode=").append(regtypecode);
        sb.append(", subjectrelationcode=").append(subjectrelationcode);
        sb.append(", depreciationcode=").append(depreciationcode);
        sb.append(", gbtradecode=").append(gbtradecode);
        sb.append(", managecode=").append(managecode);
        sb.append(", managedoubulecode=").append(managedoubulecode);
        sb.append(", budgetlevelcode=").append(budgetlevelcode);
        sb.append(", accountingmodecode=").append(accountingmodecode);
        sb.append(", issingletax=").append(issingletax);
        sb.append(", enterprisesortcode=").append(enterprisesortcode);
        sb.append(", townsflag=").append(townsflag);
        sb.append(", practicedate=").append(practicedate);
        sb.append(", eadate=").append(eadate);
        sb.append(", taxpayertypecode=").append(taxpayertypecode);
        sb.append(", holdtypecode=").append(holdtypecode);
        sb.append(", taxpayerstatuscode=").append(taxpayerstatuscode);
        sb.append(", mainbusidesc=").append(mainbusidesc);
        sb.append(", sidebusidesc=").append(sidebusidesc);
        sb.append(", employeeqty=").append(employeeqty);
        sb.append(", incomeresidecode=").append(incomeresidecode);
        sb.append(", levycode=").append(levycode);
        sb.append(", checkattribute=").append(checkattribute);
        sb.append(", taxofficialcode=").append(taxofficialcode);
        sb.append(", soctaxpayerflag=").append(soctaxpayerflag);
        sb.append(", substituteorg=").append(substituteorg);
        sb.append(", insertdeptcode=").append(insertdeptcode);
        sb.append(", insertstaffcode=").append(insertstaffcode);
        sb.append(", acceptdate=").append(acceptdate);
        sb.append(", soctaxpayerstatus=").append(soctaxpayerstatus);
        sb.append(", soctaxpayerappdate=").append(soctaxpayerappdate);
        sb.append(", isfreightdofor=").append(isfreightdofor);
        sb.append(", freightincome=").append(freightincome);
        sb.append(", personalfeetype=").append(personalfeetype);
        sb.append(", cantoncode=").append(cantoncode);
        sb.append(", provinbranchtypecode=").append(provinbranchtypecode);
        sb.append(", firstacceptdate=").append(firstacceptdate);
        sb.append("]");
        return sb.toString();
    }
}